# Generated by Django 4.1.7 on 2023-03-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='un_campo',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]

