# Generated by Django 4.1.7 on 2023-03-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0002_post_un_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='un_campo',
        ),
    ]
